/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IDirectPaymentAddress",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDirectPaymentAddress__factory>;
    getContractFactory(
      name: "IOperatorStore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IOperatorStore__factory>;
    getContractFactory(
      name: "IProjects",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IProjects__factory>;
    getContractFactory(
      name: "ITerminal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITerminal__factory>;
    getContractFactory(
      name: "ITerminalDirectory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITerminalDirectory__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "NFTMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.NFTMarket__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;

    getContractAt(
      name: "IDirectPaymentAddress",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDirectPaymentAddress>;
    getContractAt(
      name: "IOperatorStore",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IOperatorStore>;
    getContractAt(
      name: "IProjects",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IProjects>;
    getContractAt(
      name: "ITerminal",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ITerminal>;
    getContractAt(
      name: "ITerminalDirectory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ITerminalDirectory>;
    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC721Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "ERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "NFTMarket",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.NFTMarket>;
    getContractAt(
      name: "ERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
